services:
  db:
    image: ankane/pgvector
    restart: always
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@hellopulse.fr}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8888:80"
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin
    networks:
      - app_network
    depends_on:
      - db

  minio:
    image: 'minio/minio:latest'
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
      - '8900:8900'
    volumes:
      - './volumes/minio-data:/data/minio'
    command: 'minio server /data/minio --console-address=:8900'
    networks:
      - app_network

  backend:
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5000:8000"  
    networks:
      - app_network
    depends_on:
      - db
      - minio
    volumes:
      - ./backend:/app
    environment:
      - PORT=8000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  proxy:
    image: nginx
    ports:
      - "7000:80"
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - app_network
    depends_on:
      # - frontend
      - backend

networks:
  app_network:
    driver: bridge