FROM node:23-slim AS base

# Set working directory
WORKDIR /app

# Copy lock and manifest
COPY package.json package-lock.json ./

# Install dependencies with npm using cache
RUN --mount=type=cache,id=npm,target=/root/.npm npm ci

# Copy the rest of the app
COPY . .

# Expose port
EXPOSE 3000

# Run development server
CMD ["npm", "run", "dev"]