name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Build the project
        run: go build ./...

      - name: Build Docker image (development)
        run: docker build -f Dockerfile -t myapp:dev .

      - name: Build Docker image (production)
        run: docker build -f Dockerfile.prod -t myapp:prod .
