name: AI Service CI

on:
  push:
    branches: [main, dev]
    paths:
      - 'ai-service/**'
  pull_request:
    branches: [main, dev]
    paths:
      - 'ai-service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install UV (Fast Python package manager)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH # Ensure uv is in PATH
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        working-directory: ./ai-service
        run: |
          uv venv .venv
          uv pip install --python .venv/bin/python -r requirements.txt
          uv pip install --python .venv/bin/python pytest pytest-asyncio ruff mypy
      
      # - name: Run linters
      #   working-directory: ./ai-service
      #   run: |
      #     uv run --python .venv/bin/python ruff check .
      #     uv run --python .venv/bin/python mypy --show-error-codes .
      
      # - name: Run tests
      #   working-directory: ./ai-service
      #   run: |
      #     uv run --python .venv/bin/python pytest -xvs tests/